import type { Offer } from './types'

/**
 * Seed offers for Leavely Perks.
 * Affiliate URLs are placeholders pointing to merchant homepages — they are
 * intended to be auto-rewritten by Skimlinks JS once approved, or replaced
 * with deep affiliate links per network as integrations come online.
 */
export const OFFERS: Offer[] = [
  // Gym & fitness
  {
    id: 'puregym-corporate',
    merchant: 'PureGym',
    merchantSlug: 'puregym',
    title: 'Up to 25% off PureGym monthly memberships',
    category: 'gym-fitness',
    discount: 'Up to 25% off',
    discountValue: 25,
    description: 'No-contract gym access at 350+ UK clubs. Group rates available for teams of 5+ and an introductory offer on individual memberships through corporate partners.',
    ctaUrl: 'https://www.puregym.com/corporate/',
    affiliateProvider: 'direct',
    expires: '2026-12-31',
    terms: 'New members only. Joining fee may apply. Corporate scheme requires verification.',
    featured: true,
    trending: true,
    logoBg: 'bg-yellow-400',
    logoText: 'PG',
    logoColor: 'text-black',
    updatedAt: '2026-05-07',
  },
  {
    id: 'gymshark-staff',
    merchant: 'Gymshark',
    merchantSlug: 'gymshark',
    title: '15% off Gymshark workout gear',
    category: 'gym-fitness',
    discount: '15% off',
    discountValue: 15,
    description: 'Discount on the full Gymshark range — leggings, training tops, accessories — sitewide, redeemable on a unique partner code.',
    ctaUrl: 'https://uk.gymshark.com',
    affiliateProvider: 'awin',
    expires: '2026-12-31',
    terms: 'Single-use code per employee. Excludes already-discounted lines.',
    featured: true,
    logoBg: 'bg-black',
    logoText: 'GS',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'peloton-app',
    merchant: 'Peloton App',
    merchantSlug: 'peloton-app',
    title: '3 months free Peloton App membership',
    category: 'gym-fitness',
    discount: '3 months free',
    description: 'Thousands of on-demand classes — strength, yoga, running, meditation — at home or in the gym. No bike required.',
    ctaUrl: 'https://www.onepeloton.co.uk/app',
    affiliateProvider: 'direct',
    terms: 'New users only. Auto-renews after the trial unless cancelled.',
    logoBg: 'bg-red-600',
    logoText: 'P',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'classpass-staff',
    merchant: 'ClassPass',
    merchantSlug: 'classpass',
    title: '£40 off ClassPass for new members',
    category: 'gym-fitness',
    discount: '£40 off',
    description: 'A single subscription that books classes at thousands of UK studios — yoga, spin, boxing, climbing — plus on-demand sessions.',
    ctaUrl: 'https://classpass.com',
    affiliateProvider: 'impact',
    terms: 'New ClassPass members only. £40 redeemed against the first month.',
    logoBg: 'bg-yellow-300',
    logoText: 'CP',
    logoColor: 'text-black',
    updatedAt: '2026-05-07',
  },

  // Tech
  {
    id: 'apple-edu',
    merchant: 'Apple',
    merchantSlug: 'apple',
    title: 'Apple education and business pricing',
    category: 'tech-electronics',
    discount: 'Up to 10% off',
    discountValue: 10,
    description: 'MacBooks, iPads and accessories at Apple\'s business or education rate when staff order through the partner portal.',
    ctaUrl: 'https://www.apple.com/uk/shop/buy-mac/business',
    affiliateProvider: 'direct',
    terms: 'Eligibility verification required. AppleCare not included unless added.',
    featured: true,
    logoBg: 'bg-gray-900',
    logoText: '',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'currys-staff',
    merchant: 'Currys',
    merchantSlug: 'currys',
    title: '£25 off £200+ at Currys',
    category: 'tech-electronics',
    discount: '£25 off £200+',
    description: 'TVs, laptops, kitchen tech and home appliances. Stack with Currys clearance lines for big savings on home-office upgrades.',
    ctaUrl: 'https://www.currys.co.uk',
    affiliateProvider: 'awin',
    terms: 'Minimum spend £200. Excludes gift cards and a small list of MSRP-locked items.',
    trending: true,
    logoBg: 'bg-purple-700',
    logoText: 'C',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'samsung-epp',
    merchant: 'Samsung',
    merchantSlug: 'samsung',
    title: 'Samsung Employee Purchase Programme',
    category: 'tech-electronics',
    discount: 'Up to 30% off',
    discountValue: 30,
    description: 'Samsung\'s EPP unlocks staff pricing on Galaxy phones, tablets, TVs and home appliances when verified through a workplace portal.',
    ctaUrl: 'https://shop.samsung.com/uk/epp',
    affiliateProvider: 'direct',
    terms: 'Workplace verification required. Stock-dependent. Caps on certain product lines.',
    featured: true,
    logoBg: 'bg-blue-700',
    logoText: 'S',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'dell-advantage',
    merchant: 'Dell',
    merchantSlug: 'dell',
    title: 'Dell Member Purchase Program',
    category: 'tech-electronics',
    discount: 'Up to 12% off',
    discountValue: 12,
    description: 'XPS laptops, monitors and docking stations at member-tier pricing for employees of partnered businesses.',
    ctaUrl: 'https://www.dell.com/en-uk/dfh/mpp',
    affiliateProvider: 'cj',
    terms: 'Eligibility check required. Some clearance lines excluded.',
    logoBg: 'bg-blue-600',
    logoText: 'D',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'logitech-staff',
    merchant: 'Logitech',
    merchantSlug: 'logitech',
    title: '20% off Logitech home-office accessories',
    category: 'tech-electronics',
    discount: '20% off',
    discountValue: 20,
    description: 'Mice, keyboards, webcams and conference kit. The classic upgrade pack for a serious home-working setup.',
    ctaUrl: 'https://www.logitech.com/en-gb',
    affiliateProvider: 'awin',
    terms: 'Single-use code. Cannot combine with other promotions.',
    logoBg: 'bg-blue-500',
    logoText: 'L',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },

  // Food & drink
  {
    id: 'deliveroo-plus',
    merchant: 'Deliveroo',
    merchantSlug: 'deliveroo',
    title: '50% off Deliveroo Plus for 3 months',
    category: 'food-drink',
    discount: '50% off',
    discountValue: 50,
    description: 'Free delivery on orders over £15 and member-only restaurant deals across the UK.',
    ctaUrl: 'https://deliveroo.co.uk/plus',
    affiliateProvider: 'awin',
    terms: 'New Deliveroo Plus members. Auto-renews at standard price after the promotion.',
    trending: true,
    logoBg: 'bg-teal-500',
    logoText: 'D',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'gousto-staff',
    merchant: 'Gousto',
    merchantSlug: 'gousto',
    title: '60% off first Gousto box + 30% off month one',
    category: 'food-drink',
    discount: '60% off first box',
    discountValue: 60,
    description: 'UK\'s biggest recipe-box service. Curated meal kits for one to four people, delivered with everything pre-portioned.',
    ctaUrl: 'https://www.gousto.co.uk',
    affiliateProvider: 'awin',
    terms: 'New customers only. Subscription auto-renews at full price after the promo.',
    featured: true,
    logoBg: 'bg-pink-500',
    logoText: 'G',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'cafe-nero-staff',
    merchant: 'Caffè Nero',
    merchantSlug: 'cafe-nero',
    title: '20% off Caffè Nero for verified staff',
    category: 'food-drink',
    discount: '20% off',
    discountValue: 20,
    description: 'Discount on hot drinks and food in over 600 UK stores when ordering through the partner app.',
    ctaUrl: 'https://caffenero.com/uk/',
    affiliateProvider: 'direct',
    terms: 'In-app ordering only. Excludes loyalty stamp earnings.',
    logoBg: 'bg-blue-900',
    logoText: 'CN',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },

  // Fuel & supermarket
  {
    id: 'tesco-clubcard',
    merchant: 'Tesco',
    merchantSlug: 'tesco',
    title: '£15 cashback on £100+ Tesco grocery shop',
    category: 'fuel-supermarket',
    discount: '£15 cashback',
    description: 'Stack with Clubcard prices for the biggest weekly shop savings of any UK supermarket scheme.',
    ctaUrl: 'https://www.tesco.com',
    affiliateProvider: 'awin',
    terms: 'Single redemption per household. Minimum £100 basket.',
    featured: true,
    trending: true,
    logoBg: 'bg-blue-600',
    logoText: 'T',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'sainsburys-fuel',
    merchant: 'Sainsbury\'s',
    merchantSlug: 'sainsburys',
    title: '5p per litre off Sainsbury\'s fuel',
    category: 'fuel-supermarket',
    discount: '5p / litre',
    description: 'Available at the 300+ Sainsbury\'s petrol forecourts when paired with a £60 in-store grocery shop.',
    ctaUrl: 'https://www.sainsburys.co.uk',
    affiliateProvider: 'direct',
    terms: 'Voucher prints with a qualifying receipt. 14-day expiry.',
    logoBg: 'bg-orange-500',
    logoText: 'S',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'shell-go-plus',
    merchant: 'Shell Go+',
    merchantSlug: 'shell',
    title: '3% cashback on Shell fuel + 10% off Costa',
    category: 'fuel-supermarket',
    discount: '3% fuel cashback',
    description: 'Shell Go+ gives running cashback on fuel plus partner discounts at Costa, Waitrose deli counters and more.',
    ctaUrl: 'https://www.shell.co.uk/motorist/shell-go-plus.html',
    affiliateProvider: 'direct',
    terms: 'Sign up free. Cashback paid in fuel credit, redeemable at Shell forecourts.',
    logoBg: 'bg-yellow-400',
    logoText: 'Sh',
    logoColor: 'text-red-700',
    updatedAt: '2026-05-07',
  },

  // Fashion
  {
    id: 'asos-discount',
    merchant: 'ASOS',
    merchantSlug: 'asos',
    title: '20% off everything at ASOS',
    category: 'fashion',
    discount: '20% off',
    discountValue: 20,
    description: 'Sitewide ASOS discount across 850+ brands, including ASOS Design and the Premier next-day shipping pass.',
    ctaUrl: 'https://www.asos.com/men',
    affiliateProvider: 'awin',
    terms: 'Excludes premium brands listed at checkout.',
    trending: true,
    logoBg: 'bg-black',
    logoText: 'A',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'next-staff',
    merchant: 'Next',
    merchantSlug: 'next',
    title: '15% off Next clothing & home',
    category: 'fashion',
    discount: '15% off',
    discountValue: 15,
    description: 'Next\'s entire range, including Next Home and Lipsy, with free next-day delivery on orders over £30.',
    ctaUrl: 'https://www.next.co.uk',
    affiliateProvider: 'awin',
    terms: 'Excludes gift cards and clearance.',
    logoBg: 'bg-gray-900',
    logoText: 'N',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'jdsports-staff',
    merchant: 'JD Sports',
    merchantSlug: 'jd-sports',
    title: '10% off JD Sports footwear & apparel',
    category: 'fashion',
    discount: '10% off',
    discountValue: 10,
    description: 'Adidas, Nike, New Balance and JD exclusives. Stack with sale prices for serious savings on trainers.',
    ctaUrl: 'https://www.jdsports.co.uk',
    affiliateProvider: 'awin',
    terms: 'Excludes a small list of MSRP-locked launches.',
    logoBg: 'bg-red-600',
    logoText: 'JD',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },

  // Travel
  {
    id: 'booking-perks',
    merchant: 'Booking.com',
    merchantSlug: 'booking',
    title: '12% off hotels at Booking.com',
    category: 'travel',
    discount: '12% off',
    discountValue: 12,
    description: 'Stacks with Genius loyalty and seasonal sales. Particularly strong on UK weekend breaks and European city trips.',
    ctaUrl: 'https://www.booking.com',
    affiliateProvider: 'impact',
    terms: 'Bookings made via the partner portal. Excludes a small list of partner hotels.',
    featured: true,
    logoBg: 'bg-blue-700',
    logoText: 'B',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'expedia-staff',
    merchant: 'Expedia',
    merchantSlug: 'expedia',
    title: '£75 off £750+ Expedia package holidays',
    category: 'travel',
    discount: '£75 off',
    description: 'Hotel + flight bundles globally. Best value when booked 6–12 weeks in advance.',
    ctaUrl: 'https://www.expedia.co.uk',
    affiliateProvider: 'awin',
    terms: 'Minimum spend £750. Excludes peak school-holiday weeks.',
    logoBg: 'bg-yellow-400',
    logoText: 'E',
    logoColor: 'text-blue-700',
    updatedAt: '2026-05-07',
  },
  {
    id: 'enterprise-corporate',
    merchant: 'Enterprise',
    merchantSlug: 'enterprise',
    title: '15% off Enterprise car hire',
    category: 'travel',
    discount: '15% off',
    discountValue: 15,
    description: 'Domestic and international hire. Pairs well with weekend holiday breaks where rail is impractical.',
    ctaUrl: 'https://www.enterprise.co.uk',
    affiliateProvider: 'awin',
    terms: 'Subject to availability and corporate code being valid at booking.',
    logoBg: 'bg-green-700',
    logoText: 'e',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },

  // Family / kids
  {
    id: 'merlin-annual-pass',
    merchant: 'Merlin Annual Pass',
    merchantSlug: 'merlin',
    title: '15% off Merlin Annual Pass',
    category: 'family-kids',
    discount: '15% off',
    discountValue: 15,
    description: 'Unlimited entry to Alton Towers, Legoland, Thorpe Park, SEA LIFE and more. Pays for itself after two day-trips.',
    ctaUrl: 'https://www.merlinannualpass.co.uk',
    affiliateProvider: 'awin',
    terms: 'Standard Pass and above. Excludes payment-plan add-ons.',
    featured: true,
    logoBg: 'bg-purple-700',
    logoText: 'M',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'jojo-maman',
    merchant: 'JoJo Maman Bébé',
    merchantSlug: 'jojo',
    title: '20% off JoJo Maman Bébé maternity & kidswear',
    category: 'family-kids',
    discount: '20% off',
    discountValue: 20,
    description: 'British family clothing brand — pregnancy, baby and kidswear up to age 12.',
    ctaUrl: 'https://www.jojomamanbebe.co.uk',
    affiliateProvider: 'awin',
    terms: 'Single-use code. Excludes sale lines.',
    logoBg: 'bg-pink-300',
    logoText: 'JJ',
    logoColor: 'text-pink-900',
    updatedAt: '2026-05-07',
  },

  // Wellbeing
  {
    id: 'calm-app',
    merchant: 'Calm',
    merchantSlug: 'calm',
    title: '40% off Calm Premium for one year',
    category: 'wellbeing-health',
    discount: '40% off',
    discountValue: 40,
    description: 'Sleep stories, meditation, masterclasses and breathing exercises. The most-used wellbeing app in UK workplaces.',
    ctaUrl: 'https://www.calm.com',
    affiliateProvider: 'impact',
    terms: 'New Premium subscriptions. Renews at full price.',
    featured: true,
    logoBg: 'bg-indigo-600',
    logoText: 'C',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'spectrum-health',
    merchant: 'Spectrum.Life',
    merchantSlug: 'spectrum-life',
    title: 'Free 24/7 EAP and counselling sessions',
    category: 'wellbeing-health',
    discount: 'Free for staff',
    description: 'Confidential employee assistance programme — counselling, legal and financial advice. A genuine clinical-grade benefit, not a wellness app.',
    ctaUrl: 'https://www.spectrum.life',
    affiliateProvider: 'direct',
    terms: 'Provided to participating employers. Includes structured CBT pathways.',
    logoBg: 'bg-teal-600',
    logoText: 'SL',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'specsavers-corp',
    merchant: 'Specsavers Corporate',
    merchantSlug: 'specsavers',
    title: 'Free DSE eyetests for VDU users',
    category: 'wellbeing-health',
    discount: 'Free eyetest',
    description: 'Health & Safety legislation requires DSE-user eyetests. Specsavers Corporate covers them at zero cost to staff and a flat fee per voucher.',
    ctaUrl: 'https://corporate.specsavers.co.uk',
    affiliateProvider: 'direct',
    terms: 'Voucher activated by employer. Includes contribution toward glasses required for DSE work.',
    logoBg: 'bg-green-700',
    logoText: 'Sp',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },

  // Mobile
  {
    id: 'ctn-business-mobile',
    merchant: 'Compare The Networks',
    merchantSlug: 'compare-the-networks',
    title: 'Up to 35% off business mobile plans',
    category: 'mobile-broadband',
    discount: 'Up to 35% off',
    discountValue: 35,
    description: 'Negotiated O2, Vodafone and EE business tariffs. Often beats consumer SIM-only plans, with a single bill across the whole team.',
    ctaUrl: 'https://comparethenetworks.com',
    affiliateProvider: 'direct',
    terms: 'Subject to credit check. Three-network sign-up via separate flow.',
    featured: true,
    trending: true,
    logoBg: 'bg-emerald-600',
    logoText: 'CTN',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'sky-broadband',
    merchant: 'Sky Broadband',
    merchantSlug: 'sky-broadband',
    title: '£100 reward voucher with Sky Broadband',
    category: 'mobile-broadband',
    discount: '£100 voucher',
    description: 'Available on selected Superfast and Gigafast plans, plus a 12-month price guarantee.',
    ctaUrl: 'https://www.sky.com/broadband',
    affiliateProvider: 'awin',
    terms: 'New Sky Broadband customers. Voucher delivered after first bill.',
    logoBg: 'bg-blue-700',
    logoText: 'Sk',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },

  // Home & utilities
  {
    id: 'octopus-energy',
    merchant: 'Octopus Energy',
    merchantSlug: 'octopus',
    title: '£50 credit on Octopus Energy switch',
    category: 'home-utilities',
    discount: '£50 credit',
    description: 'Renewable-led UK energy supplier with a strong customer-service reputation. £50 added to your account on first bill.',
    ctaUrl: 'https://octopus.energy',
    affiliateProvider: 'awin',
    terms: 'New customers only. Switch usually completes within 21 days.',
    featured: true,
    logoBg: 'bg-purple-700',
    logoText: 'O',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
  {
    id: 'compare-the-market',
    merchant: 'Compare the Market',
    merchantSlug: 'compare-the-market',
    title: '2-for-1 cinema tickets every Tuesday & Wednesday',
    category: 'home-utilities',
    discount: '2-for-1',
    description: 'Quote any insurance policy and unlock Meerkat Movies — 2-for-1 cinema tickets twice a week for a full year.',
    ctaUrl: 'https://www.comparethemarket.com/meerkat-movies/',
    affiliateProvider: 'direct',
    terms: 'Requires a qualifying insurance quote. Not valid for every cinema chain.',
    logoBg: 'bg-blue-600',
    logoText: 'CtM',
    logoColor: 'text-white',
    updatedAt: '2026-05-07',
  },
]

export function getOffer(id: string): Offer | undefined {
  return OFFERS.find((o) => o.id === id)
}

export function getOffersByCategory(category: string): Offer[] {
  return OFFERS.filter((o) => o.category === category)
}

export function getFeaturedOffers(): Offer[] {
  return OFFERS.filter((o) => o.featured)
}

export function getTrendingOffers(): Offer[] {
  return OFFERS.filter((o) => o.trending)
}
